Document: t50
Title: Debian t50 Manual
Author: <insert document author here>
Abstract: This manual describes what t50 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/t50/t50.sgml.gz

Format: postscript
Files: /usr/share/doc/t50/t50.ps.gz

Format: text
Files: /usr/share/doc/t50/t50.text.gz

Format: HTML
Index: /usr/share/doc/t50/html/index.html
Files: /usr/share/doc/t50/html/*.html
